# This workflow will build a PR using Maven and then upload the test results

name: CI
on:
  push:
    branches: [ '!master' ]
  pull_request:
    branches: [ master ]
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # ignoring target, tests, ui project POMs (very few changes, if any)
      - name: Build with Maven
        run: mvn -B verify -f pom.xml
